### ISSUE TITLE
It doesn't work for Oracle 12c

### ISSUE THREAD

**Issue by lkvn01** [mbleron/ExcelTable#10]
Under Oracle 12c generates error during creating jar exceldbtools-1.6.jar
---
Error while creating jar java/lib/sjsxp-1.0.2.jar
ORA-06550:... 25:
PLS-00302 component 'FINISH_LOADING_JAR' must be declared

**Comment by mbleron** [comment]
> Error while creating jar java/lib/sjsxp-1.0.2.jar

If you're on Oracle 12 then you must NOT load sjsxp-1.0.2.jar.
It's clearly explained in the [README](https://github.com/mbleron/ExcelTable/blob/master/README.md).

About the actual error : 
> PLS-00302 component 'FINISH_LOADING_JAR' must be declared

That's because you're not using the correct version of the loadjava utility.
You need loadjava from a **12c** client.

**Comment by mbleron** [comment]
Closing this (installation issue).
